services:
  cdn:
    container_name: cdn
    image: cdn
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      .env
    ports:
      - "8501:8080"

  postgres:
    image: postgres:15
    container_name: cdn_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-cdn}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB:-cdn}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8502:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cdn -d cdn"]
      interval: 5s
      retries: 5

  cdn_cron:
    container_name: cdn_cron
    image: alpine-base
    build:
      context: ./cron
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_USER: cdn
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: cdn
      DB_HOST: postgres
    restart: always

volumes:
  postgres_data:
